os: osx
language: generic
osx_image: xcode8  # OS X 10.10
env:
  - PYTHON_VERSION=2 PYTHON_INSTALL_METHOD=system
matrix:
  include:
    - env:
      - PYTHON_VERSION="pypy-5.0.0 2.7.12"
      - PYTHON_INSTALL_METHOD=tox
      - TEST_NUMBER=1
    - env:
      - PYTHON_VERSION="3.5.2 3.4.5"
      - PYTHON_INSTALL_METHOD=tox
      - TEST_NUMBER=2
    - env:
      - PYTHON_VERSION=2.7
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.4
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.5
      - PYTHON_INSTALL_METHOD=macpython
    - osx_image: xcode7.3  # OS X 10.11
    - osx_image: xcode8.2 # macOS 10.12
  allow_failures:
    - osx_image: xcode8.2
cache:
  directories:
  - $HOME/.pyenv
install:
  - "source travis/install.sh"

script:
  - "source travis/script.sh"

after_success:
  - pip install codecov
  - codecov

notifications:
  email: false
